# Generated by Django 4.0 on 2021-12-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dictionary', '0002_vocab_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocab',
            name='user_id',
        ),
        migrations.AddField(
            model_name='vocab',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
